[metric_to_imperial]
# Multiply each non-null daily PCE_Production value before POST to Whitson+
gathered_gas_e3m3_per_day_to_mcf_per_day =35.49373
condensate_m3_per_day_to_bbl_per_day =6.29287
gath_water_m3_per_day_to_bbl_per_day = 6.29010
tubing_pressure_kpa_to_psi =0.145038
casing_pressure_kpa_to_psi =0.145038
choke_size_multiplier = 0.03937
